-- =============================================================================
-- AI Sales CRM: first-time database setup for a NEW Supabase project.
--
-- GENERATED by `npm run db:setup-sql` from supabase/migrations. Do not edit.
-- Migrations: 20261005120000, 20261005120100, 20261006120000, 20261007120000, 20261008120000, 20261009120000, 20261010120000, 20261011120000, 20261012120000, 20261013120000, 20261014120000
--
-- How to use: Supabase dashboard → SQL Editor → New query → paste this whole
-- file → Run. It runs in one transaction (all or nothing), refuses to run if
-- the CRM tables already exist, and records the migrations in
-- supabase_migrations.schema_migrations so `supabase db push` keeps working
-- for future migrations. No demo/seed data and no users are created.
-- =============================================================================

begin;

do $setup$
begin
  if to_regclass('public.prospects') is not null then
    raise exception 'The CRM tables already exist in this project. This script is for a new project only; apply new migrations with "npx supabase db push".';
  end if;
end
$setup$;

-- -----------------------------------------------------------------------------
-- 20261005120000_schema.sql
-- -----------------------------------------------------------------------------

-- AI Sales CRM V1: schema (enums, tables, constraints, indexes).
-- SPEC.md §2–§9 is the source of truth. Functions, triggers and the flags view
-- live in the next migration; RLS is added in Prompt 2.

-- ---------------------------------------------------------------------------
-- Enums (exact SPEC values and order; mirrored in src/lib/constants.ts)
-- ---------------------------------------------------------------------------
create type public.pipeline_stage as enum (
  'prospect',
  'contacted',
  'conversation',
  'qualified',
  'demo_booked',
  'demo_attended',
  'follow_up',
  'closed_won',
  'closed_lost'
);

create type public.decision_maker_status as enum ('yes', 'no', 'unknown');

create type public.objection_category as enum (
  'price',
  'timing',
  'competitor',
  'budget',
  'no_authority',
  'not_interested',
  'other'
);

create type public.activity_type as enum (
  'call',
  'conversation',
  'note',
  'demo',
  'follow_up',
  'stage_change',
  'owner_change',
  'ai_insight'
);

create type public.follow_up_status as enum ('pending', 'completed');

create type public.deal_health as enum ('high', 'medium', 'low');

create type public.user_role as enum ('manager', 'sales_rep');

-- ---------------------------------------------------------------------------
-- users: one row per auth user (created by the handle_new_user trigger)
-- ---------------------------------------------------------------------------
create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null default '',
  email text not null,
  role public.user_role not null default 'sales_rep',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.users.role is
  'Mirrors auth.users.raw_app_meta_data.role. Never taken from user-editable metadata.';

-- ---------------------------------------------------------------------------
-- org_settings: exactly one row (id = true)
-- ---------------------------------------------------------------------------
create table public.org_settings (
  id boolean primary key default true,
  default_currency char(3) not null default 'USD',
  timezone text not null default 'America/New_York',
  stale_days integer not null default 14,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.users (id) on delete set null,
  constraint org_settings_single_row check (id),
  constraint org_settings_currency_check check (default_currency ~ '^[A-Z]{3}$'),
  constraint org_settings_timezone_check check (
    timezone in (
      'America/New_York',
      'America/Chicago',
      'America/Denver',
      'America/Phoenix',
      'America/Los_Angeles',
      'America/Anchorage',
      'Pacific/Honolulu'
    )
  ),
  constraint org_settings_stale_days_check check (stale_days between 1 and 365)
);

insert into public.org_settings default values on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- prospects
-- ---------------------------------------------------------------------------
create table public.prospects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  company text,
  email text,
  phone text,
  stage public.pipeline_stage not null default 'prospect',
  decision_maker_status public.decision_maker_status not null default 'unknown',
  objections public.objection_category[] not null default '{}',
  objection_notes text,
  notes text,
  -- Derived: earliest pending follow-up due date (maintained by a trigger).
  follow_up_date date,
  demo_at timestamptz,
  close_reason text,
  close_notes text,
  closed_at timestamptz,
  deal_value numeric(12, 2),
  currency char(3) not null,
  owner_id uuid not null references public.users (id) on delete restrict,
  created_by uuid default auth.uid() references public.users (id) on delete set null,
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint prospects_name_check check (btrim(name) <> ''),
  constraint prospects_currency_check check (currency ~ '^[A-Z]{3}$'),
  constraint prospects_deal_value_check check (deal_value >= 0),
  constraint prospects_close_reason_check check (
    case stage
      when 'closed_won' then close_reason is not null
        and close_reason in ('product_fit', 'price_value', 'relationship', 'urgent_need', 'other')
      when 'closed_lost' then close_reason is not null
        and close_reason in ('price', 'timing', 'competitor', 'no_budget', 'no_response', 'not_a_fit', 'other')
      else close_reason is null
    end
  ),
  constraint prospects_closed_fields_check check (
    (stage in ('closed_won', 'closed_lost')) = (closed_at is not null)
    and (stage in ('closed_won', 'closed_lost') or close_notes is null)
  )
);

comment on column public.prospects.follow_up_date is
  'Derived: min(due_date) of pending follow_ups. Managed by trigger; never edit directly.';

-- ---------------------------------------------------------------------------
-- activities (append-only timeline)
-- ---------------------------------------------------------------------------
create table public.activities (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid not null references public.prospects (id) on delete cascade,
  user_id uuid default auth.uid() references public.users (id) on delete set null,
  type public.activity_type not null,
  content text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- follow_ups
-- ---------------------------------------------------------------------------
create table public.follow_ups (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid not null references public.prospects (id) on delete cascade,
  owner_id uuid not null references public.users (id) on delete restrict,
  due_date date not null,
  note text not null,
  status public.follow_up_status not null default 'pending',
  completed_at timestamptz,
  completed_by uuid references public.users (id) on delete set null,
  created_by uuid default auth.uid() references public.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint follow_ups_completed_check check ((status = 'completed') = (completed_at is not null))
);

-- ---------------------------------------------------------------------------
-- stage_history (append-only; written by triggers)
-- ---------------------------------------------------------------------------
create table public.stage_history (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid not null references public.prospects (id) on delete cascade,
  from_stage public.pipeline_stage,
  to_stage public.pipeline_stage not null,
  -- Null only for seed/system writes.
  changed_by uuid references public.users (id) on delete set null,
  changed_at timestamptz not null default now(),
  close_reason text,
  note text
);

-- ---------------------------------------------------------------------------
-- ai_insights (append-only)
-- ---------------------------------------------------------------------------
create table public.ai_insights (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid not null references public.prospects (id) on delete cascade,
  summary text not null,
  decision_maker_status public.decision_maker_status not null,
  main_objection text not null,
  recommended_next_step text not null,
  deal_health public.deal_health not null,
  model text not null,
  created_by uuid default auth.uid() references public.users (id) on delete set null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Indexes (every FK column is the leading column of some index)
-- ---------------------------------------------------------------------------
create index org_settings_updated_by_idx on public.org_settings (updated_by);

create index prospects_owner_id_idx on public.prospects (owner_id);
create index prospects_stage_idx on public.prospects (stage);
create index prospects_follow_up_date_idx on public.prospects (follow_up_date);
create index prospects_last_activity_at_idx on public.prospects (last_activity_at);
create index prospects_created_by_idx on public.prospects (created_by);

create index activities_prospect_id_occurred_at_idx on public.activities (prospect_id, occurred_at desc);
create index activities_user_id_idx on public.activities (user_id);

create index follow_ups_status_due_date_idx on public.follow_ups (status, due_date);
create index follow_ups_owner_id_idx on public.follow_ups (owner_id);
create index follow_ups_prospect_id_idx on public.follow_ups (prospect_id);
create index follow_ups_completed_by_idx on public.follow_ups (completed_by);
create index follow_ups_created_by_idx on public.follow_ups (created_by);

create index stage_history_prospect_id_changed_at_idx on public.stage_history (prospect_id, changed_at);
create index stage_history_changed_by_idx on public.stage_history (changed_by);

create index ai_insights_prospect_id_created_at_idx on public.ai_insights (prospect_id, created_at desc);
create index ai_insights_created_by_created_at_idx on public.ai_insights (created_by, created_at);

-- -----------------------------------------------------------------------------
-- 20261005120100_functions_triggers.sql
-- -----------------------------------------------------------------------------

-- AI Sales CRM V1: helper functions, triggers, flags view and stage-change RPC.
-- Conventions: every function sets search_path = '' and schema-qualifies all
-- objects. Trigger functions that write to other tables are SECURITY DEFINER
-- so they keep working once RLS (Prompt 2) blocks direct writes.
-- auth.uid() is null for seed/system/service-role writes; that is handled
-- explicitly below.

-- ---------------------------------------------------------------------------
-- Generic helpers
-- ---------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- True when the current user is a manager (false when auth.uid() is null).
create or replace function public.is_manager()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.users u
    where u.id = auth.uid() and u.role = 'manager'
  );
$$;

-- "Today" in the org timezone (SPEC §6).
create or replace function public.org_today()
returns date
language sql
stable
security definer
set search_path = ''
as $$
  select (now() at time zone s.timezone)::date
  from public.org_settings s
  where s.id;
$$;

-- ---------------------------------------------------------------------------
-- org_settings
-- ---------------------------------------------------------------------------
create or replace function public.org_settings_before_update()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_by := coalesce(auth.uid(), new.updated_by);
  return new;
end;
$$;

create trigger org_settings_set_updated_at
  before update on public.org_settings
  for each row execute function public.set_updated_at();

create trigger org_settings_before_update
  before update on public.org_settings
  for each row execute function public.org_settings_before_update();

-- ---------------------------------------------------------------------------
-- users: creation from auth.users, role/email sync, last-manager guard
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.users (id, email, full_name, role)
  values (
    new.id,
    coalesce(new.email, ''),
    coalesce(
      nullif(btrim(new.raw_user_meta_data ->> 'full_name'), ''),
      split_part(coalesce(new.email, ''), '@', 1)
    ),
    -- The role is only ever read from raw_app_meta_data (not user-editable).
    case
      when new.raw_app_meta_data ->> 'role' in ('manager', 'sales_rep')
        then (new.raw_app_meta_data ->> 'role')::public.user_role
      else 'sales_rep'::public.user_role
    end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Keeps public.users in sync when auth email or app_metadata.role changes
-- (e.g. invite → auth.admin.updateUserById({ app_metadata: { role } })).
create or replace function public.handle_auth_user_updated()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.email is not null then
    update public.users u
       set email = new.email
     where u.id = new.id
       and u.email is distinct from new.email;
  end if;

  if new.raw_app_meta_data ->> 'role' in ('manager', 'sales_rep') then
    update public.users u
       set role = (new.raw_app_meta_data ->> 'role')::public.user_role
     where u.id = new.id
       and u.role is distinct from (new.raw_app_meta_data ->> 'role')::public.user_role;
  end if;

  return null;
end;
$$;

create trigger on_auth_user_updated
  after update of email, raw_app_meta_data on auth.users
  for each row execute function public.handle_auth_user_updated();

-- Mirrors public.users.role into auth.users.raw_app_meta_data.role.
create or replace function public.sync_user_role_to_auth()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  update auth.users a
     set raw_app_meta_data = coalesce(a.raw_app_meta_data, '{}'::jsonb)
                             || jsonb_build_object('role', new.role::text)
   where a.id = new.id
     and (a.raw_app_meta_data ->> 'role') is distinct from new.role::text;
  return null;
end;
$$;

create trigger users_sync_role_to_auth
  after update of role on public.users
  for each row
  when (old.role is distinct from new.role)
  execute function public.sync_user_role_to_auth();

-- At least one manager must always exist (SPEC §4).
create or replace function public.protect_last_manager()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.role = 'manager'
     and (tg_op = 'DELETE' or new.role is distinct from 'manager'::public.user_role) then
    -- Serialise concurrent demotions/deletions of managers.
    perform pg_advisory_xact_lock(hashtext('public.users.last_manager'));
    if not exists (
      select 1 from public.users u
      where u.role = 'manager' and u.id <> old.id
    ) then
      raise exception 'At least one manager must remain'
        using errcode = 'P0001',
              hint = 'Promote another user to manager first.';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger users_protect_last_manager_update
  before update of role on public.users
  for each row execute function public.protect_last_manager();

create trigger users_protect_last_manager_delete
  before delete on public.users
  for each row execute function public.protect_last_manager();

create trigger users_set_updated_at
  before update on public.users
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- prospects
-- ---------------------------------------------------------------------------
create or replace function public.prospects_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.currency is null then
    select s.default_currency into new.currency
    from public.org_settings s
    where s.id;
  end if;

  new.owner_id := coalesce(new.owner_id, auth.uid());
  new.created_by := coalesce(auth.uid(), new.created_by);

  -- follow_up_date is derived from follow_ups; a new prospect has none.
  if pg_trigger_depth() = 1 then
    new.follow_up_date := null;
  end if;

  if new.stage in ('closed_won', 'closed_lost') then
    new.closed_at := coalesce(new.closed_at, now());
  end if;

  return new;
end;
$$;

create or replace function public.prospects_before_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  -- Reassignment: managers only (auth.uid() is null for system/service writes).
  if new.owner_id is distinct from old.owner_id
     and auth.uid() is not null
     and not public.is_manager() then
    raise exception 'Only managers can reassign prospects'
      using errcode = '42501';
  end if;

  -- created_at is immutable. (created_by is not forced: the FK's
  -- "on delete set null" must still be able to clear it.)
  new.created_at := old.created_at;

  -- follow_up_date is only written by the follow_ups trigger (depth > 1).
  if pg_trigger_depth() = 1 then
    new.follow_up_date := old.follow_up_date;
  end if;

  if new.stage is distinct from old.stage then
    if new.stage in ('closed_won', 'closed_lost') then
      new.closed_at := now();
    elsif old.stage in ('closed_won', 'closed_lost') then
      -- Reopen: clear the outcome before the CHECK constraints run.
      -- stage_history keeps the old close_reason.
      new.close_reason := null;
      new.close_notes := null;
      new.closed_at := null;
    end if;
  end if;

  return new;
end;
$$;

create or replace function public.prospects_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.stage_history (prospect_id, from_stage, to_stage, changed_by, close_reason)
  values (new.id, null, new.stage, coalesce(auth.uid(), new.created_by), new.close_reason);
  return null;
end;
$$;

create or replace function public.prospects_after_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_note text := nullif(btrim(current_setting('app.stage_change_note', true)), '');
begin
  if new.stage is distinct from old.stage then
    insert into public.stage_history (prospect_id, from_stage, to_stage, changed_by, close_reason, note)
    values (new.id, old.stage, new.stage, auth.uid(), new.close_reason, v_note);

    insert into public.activities (prospect_id, user_id, type, content, metadata)
    values (
      new.id,
      auth.uid(),
      'stage_change',
      v_note,
      jsonb_build_object('from', old.stage, 'to', new.stage, 'close_reason', new.close_reason)
    );
  end if;

  if new.owner_id is distinct from old.owner_id then
    insert into public.activities (prospect_id, user_id, type, metadata)
    values (
      new.id,
      auth.uid(),
      'owner_change',
      jsonb_build_object('from_owner', old.owner_id, 'to_owner', new.owner_id)
    );

    update public.follow_ups f
       set owner_id = new.owner_id
     where f.prospect_id = new.id
       and f.status = 'pending'
       and f.owner_id is distinct from new.owner_id;
  end if;

  return null;
end;
$$;

create trigger prospects_before_insert
  before insert on public.prospects
  for each row execute function public.prospects_before_insert();

create trigger prospects_before_update
  before update on public.prospects
  for each row execute function public.prospects_before_update();

create trigger prospects_set_updated_at
  before update on public.prospects
  for each row execute function public.set_updated_at();

create trigger prospects_after_insert
  after insert on public.prospects
  for each row execute function public.prospects_after_insert();

create trigger prospects_after_update
  after update on public.prospects
  for each row
  when (old.stage is distinct from new.stage or old.owner_id is distinct from new.owner_id)
  execute function public.prospects_after_update();

-- ---------------------------------------------------------------------------
-- activities → prospects.last_activity_at (human sales activity only, SPEC §7)
-- ---------------------------------------------------------------------------
create or replace function public.activities_after_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_at timestamptz := least(new.occurred_at, now());
begin
  if new.type in ('call', 'conversation', 'note', 'demo', 'follow_up', 'stage_change') then
    update public.prospects p
       set last_activity_at = v_at
     where p.id = new.prospect_id
       and p.last_activity_at < v_at;
  end if;
  return null;
end;
$$;

create trigger activities_after_insert
  after insert on public.activities
  for each row execute function public.activities_after_insert();

-- ---------------------------------------------------------------------------
-- follow_ups → prospects.follow_up_date (earliest pending due date, SPEC §3)
-- ---------------------------------------------------------------------------
create or replace function public.refresh_prospect_follow_up_date(p_prospect_id uuid)
returns void
language sql
security definer
set search_path = ''
as $$
  update public.prospects p
     set follow_up_date = s.next_due
    from (
      select min(f.due_date) as next_due
      from public.follow_ups f
      where f.prospect_id = p_prospect_id
        and f.status = 'pending'
    ) s
   where p.id = p_prospect_id
     and p.follow_up_date is distinct from s.next_due;
$$;

revoke execute on function public.refresh_prospect_follow_up_date(uuid) from public, anon, authenticated;

create or replace function public.follow_ups_before_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.owner_id is null then
    select p.owner_id into new.owner_id
    from public.prospects p
    where p.id = new.prospect_id;
  end if;
  new.created_by := coalesce(auth.uid(), new.created_by);
  return new;
end;
$$;

create or replace function public.follow_ups_after_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE'
     and new.prospect_id = old.prospect_id
     and new.status = old.status
     and new.due_date = old.due_date then
    return null; -- nothing that affects follow_up_date changed
  end if;

  if tg_op in ('INSERT', 'UPDATE') then
    perform public.refresh_prospect_follow_up_date(new.prospect_id);
  end if;

  if tg_op = 'DELETE' or (tg_op = 'UPDATE' and new.prospect_id <> old.prospect_id) then
    perform public.refresh_prospect_follow_up_date(old.prospect_id);
  end if;

  return null;
end;
$$;

create trigger follow_ups_before_insert
  before insert on public.follow_ups
  for each row execute function public.follow_ups_before_insert();

create trigger follow_ups_set_updated_at
  before update on public.follow_ups
  for each row execute function public.set_updated_at();

create trigger follow_ups_after_change
  after insert or update or delete on public.follow_ups
  for each row execute function public.follow_ups_after_change();

-- ---------------------------------------------------------------------------
-- Stage change RPC (used by the moveProspectStage server action).
-- SECURITY INVOKER: RLS applies. Passes the optional note to the AFTER UPDATE
-- trigger via the transaction-local setting app.stage_change_note.
-- ---------------------------------------------------------------------------
create or replace function public.move_prospect_stage(
  p_prospect_id uuid,
  p_to_stage public.pipeline_stage,
  p_close_reason text default null,
  p_close_notes text default null,
  p_note text default null
)
returns public.prospects
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_row public.prospects;
  v_closed boolean := p_to_stage in ('closed_won', 'closed_lost');
begin
  select * into v_row
  from public.prospects p
  where p.id = p_prospect_id
  for update;

  if not found then
    raise exception 'Prospect not found' using errcode = 'P0002';
  end if;

  if v_row.stage = p_to_stage then
    return v_row; -- same stage: no-op, no history
  end if;

  perform set_config('app.stage_change_note', coalesce(btrim(p_note), ''), true);

  update public.prospects p
     set stage = p_to_stage,
         close_reason = case when v_closed then nullif(btrim(p_close_reason), '') end,
         close_notes = case when v_closed then nullif(btrim(p_close_notes), '') end
   where p.id = p_prospect_id
  returning * into v_row;

  perform set_config('app.stage_change_note', '', true);

  return v_row;
end;
$$;

-- ---------------------------------------------------------------------------
-- Flags view (SECURITY INVOKER so RLS on prospects applies)
-- ---------------------------------------------------------------------------
create view public.prospects_with_flags
with (security_invoker = true)
as
select
  p.*,
  coalesce(
    p.stage not in ('closed_won', 'closed_lost')
      and p.last_activity_at < now() - make_interval(days => s.stale_days),
    false
  ) as is_stale,
  coalesce(p.follow_up_date < public.org_today(), false) as has_overdue_follow_up
from public.prospects p
left join public.org_settings s on s.id;

comment on view public.prospects_with_flags is
  'prospects + is_stale (open, no human activity for org stale_days) + has_overdue_follow_up (earliest pending follow-up before org_today()).';

-- -----------------------------------------------------------------------------
-- 20261006120000_rls.sql
-- -----------------------------------------------------------------------------

-- AI Sales CRM V1: Row Level Security (SPEC §4).
-- RLS is the security boundary for every API request. Policies only call
-- SECURITY DEFINER helpers (is_manager, can_access_prospect) so they never
-- recurse into RLS on public.users / public.prospects. Grants are tightened
-- too: anon gets nothing, authenticated gets exactly what the policies need
-- (derived/system columns are not writable).

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------
-- is_manager() already exists (Prompt 1): sql, stable, security definer,
-- search_path = '', reads public.users.role for auth.uid().

-- True when the current user owns the prospect or is a manager.
-- False for unknown ids (leaks nothing).
create or replace function public.can_access_prospect(p_prospect_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.prospects p
    where p.id = p_prospect_id
      and (p.owner_id = auth.uid() or public.is_manager())
  );
$$;

-- ---------------------------------------------------------------------------
-- users: only managers change roles; users only rename themselves.
-- auth.uid() is null for the service role, GoTrue (auth.admin.updateUserById
-- → handle_auth_user_updated sync), seed and migrations: always allowed.
-- ---------------------------------------------------------------------------
create or replace function public.users_before_update_guard()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    return new;
  end if;

  if new.role is distinct from old.role and not public.is_manager() then
    raise exception 'Only managers can change roles'
      using errcode = '42501';
  end if;

  if new.full_name is distinct from old.full_name and new.id <> auth.uid() then
    raise exception 'Users can only change their own name'
      using errcode = '42501';
  end if;

  return new;
end;
$$;

create trigger users_before_update_guard
  before update on public.users
  for each row execute function public.users_before_update_guard();

-- ---------------------------------------------------------------------------
-- Enable RLS on every public table
-- ---------------------------------------------------------------------------
alter table public.users enable row level security;
alter table public.org_settings enable row level security;
alter table public.prospects enable row level security;
alter table public.activities enable row level security;
alter table public.follow_ups enable row level security;
alter table public.stage_history enable row level security;
alter table public.ai_insights enable row level security;

-- ---------------------------------------------------------------------------
-- Grants: start from nothing for the API roles, then grant what policies need
-- ---------------------------------------------------------------------------
revoke all on all tables in schema public from anon, authenticated;
revoke all on all sequences in schema public from anon, authenticated;
revoke execute on all functions in schema public from public, anon, authenticated;

-- Future objects created by postgres (migrations) never reach anon.
-- NOTE: functions still get EXECUTE via PUBLIC by default; every new function
-- must `revoke execute ... from public, anon` explicitly.
alter default privileges for role postgres in schema public revoke all on tables from anon;
alter default privileges for role postgres in schema public revoke all on sequences from anon;
alter default privileges for role postgres in schema public revoke all on functions from anon;

-- Functions callable by signed-in users (policies, view, RPC).
grant execute on function public.is_manager() to authenticated;
grant execute on function public.can_access_prospect(uuid) to authenticated;
grant execute on function public.org_today() to authenticated;
grant execute on function public.move_prospect_stage(uuid, public.pipeline_stage, text, text, text) to authenticated;

-- org_settings
grant select on public.org_settings to authenticated;
grant update (default_currency, timezone, stale_days) on public.org_settings to authenticated;

-- users (no insert/delete via the API)
grant select on public.users to authenticated;
grant update (full_name, role) on public.users to authenticated;

-- prospects (derived/system columns are not writable)
grant select, delete on public.prospects to authenticated;
grant insert (
  id, name, company, email, phone, stage, decision_maker_status, objections, objection_notes,
  notes, demo_at, close_reason, close_notes, deal_value, currency, owner_id
) on public.prospects to authenticated;
grant update (
  name, company, email, phone, stage, decision_maker_status, objections, objection_notes,
  notes, demo_at, close_reason, close_notes, deal_value, currency, owner_id
) on public.prospects to authenticated;

-- activities (append-only)
grant select on public.activities to authenticated;
grant insert (id, prospect_id, user_id, type, content, metadata, occurred_at) on public.activities to authenticated;

-- follow_ups (owner only moves via reassignment; prospect_id immutable)
grant select, delete on public.follow_ups to authenticated;
grant insert (id, prospect_id, owner_id, due_date, note, status, completed_at, completed_by)
  on public.follow_ups to authenticated;
grant update (due_date, note, status, completed_at, completed_by) on public.follow_ups to authenticated;

-- stage_history (read-only; written by security definer triggers)
grant select on public.stage_history to authenticated;

-- ai_insights (append-only; created_at not writable → rate limit can't be bypassed)
grant select on public.ai_insights to authenticated;
grant insert (
  id, prospect_id, summary, decision_maker_status, main_objection, recommended_next_step,
  deal_health, model, created_by
) on public.ai_insights to authenticated;

-- flags view (security_invoker → prospects RLS applies)
grant select on public.prospects_with_flags to authenticated;

-- ---------------------------------------------------------------------------
-- Policies (authenticated only; anon has none)
-- ---------------------------------------------------------------------------

-- org_settings
create policy org_settings_select on public.org_settings
  for select to authenticated
  using (true);

create policy org_settings_update_manager on public.org_settings
  for update to authenticated
  using ((select public.is_manager()))
  with check ((select public.is_manager()));

-- users
create policy users_select on public.users
  for select to authenticated
  using (true);

-- Own row (full_name) or managers (role); users_before_update_guard enforces
-- which columns each may change.
create policy users_update on public.users
  for update to authenticated
  using (id = (select auth.uid()) or (select public.is_manager()))
  with check (id = (select auth.uid()) or (select public.is_manager()));

-- prospects
create policy prospects_select on public.prospects
  for select to authenticated
  using (owner_id = (select auth.uid()) or (select public.is_manager()));

create policy prospects_insert on public.prospects
  for insert to authenticated
  with check (owner_id = (select auth.uid()) or (select public.is_manager()));

create policy prospects_update on public.prospects
  for update to authenticated
  using (owner_id = (select auth.uid()) or (select public.is_manager()))
  with check (owner_id = (select auth.uid()) or (select public.is_manager()));

create policy prospects_delete_manager on public.prospects
  for delete to authenticated
  using ((select public.is_manager()));

-- activities (append-only; stage_change/owner_change come from triggers only)
create policy activities_select on public.activities
  for select to authenticated
  using (public.can_access_prospect(prospect_id));

create policy activities_insert on public.activities
  for insert to authenticated
  with check (
    user_id = (select auth.uid())
    and type not in ('stage_change', 'owner_change')
    and public.can_access_prospect(prospect_id)
  );

-- follow_ups
create policy follow_ups_select on public.follow_ups
  for select to authenticated
  using (public.can_access_prospect(prospect_id));

create policy follow_ups_insert on public.follow_ups
  for insert to authenticated
  with check (public.can_access_prospect(prospect_id));

create policy follow_ups_update on public.follow_ups
  for update to authenticated
  using (public.can_access_prospect(prospect_id))
  with check (public.can_access_prospect(prospect_id));

create policy follow_ups_delete on public.follow_ups
  for delete to authenticated
  using (public.can_access_prospect(prospect_id));

-- stage_history (read-only)
create policy stage_history_select on public.stage_history
  for select to authenticated
  using (public.can_access_prospect(prospect_id));

-- ai_insights (append-only)
create policy ai_insights_select on public.ai_insights
  for select to authenticated
  using (public.can_access_prospect(prospect_id));

create policy ai_insights_insert on public.ai_insights
  for insert to authenticated
  with check (
    created_by = (select auth.uid())
    and public.can_access_prospect(prospect_id)
  );

-- ---------------------------------------------------------------------------
-- Realtime (Prompt 9 Kanban): publish prospects changes; RLS applies per
-- subscriber.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (
       select 1 from pg_publication_tables
       where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'prospects'
     ) then
    alter publication supabase_realtime add table public.prospects;
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- 20261007120000_pipeline.sql
-- -----------------------------------------------------------------------------

-- Prompt 9 (Kanban pipeline): latest AI insight per prospect + Realtime
-- notification for owner reassignment.

-- ---------------------------------------------------------------------------
-- latest_ai_insights: the newest ai_insights row per prospect (distinct on,
-- served by ai_insights_prospect_id_created_at_idx). security_invoker → the
-- caller's RLS on ai_insights applies (reps: own prospects only).
-- ---------------------------------------------------------------------------
create view public.latest_ai_insights
with (security_invoker = true)
as
select distinct on (i.prospect_id)
  i.prospect_id,
  i.id,
  i.deal_health,
  i.created_at
from public.ai_insights i
order by i.prospect_id, i.created_at desc, i.id desc;

comment on view public.latest_ai_insights is
  'Newest AI insight per prospect (deal_health for Kanban cards / dashboard). security_invoker: RLS of ai_insights applies.';

revoke all on public.latest_ai_insights from public, anon, authenticated;
grant select on public.latest_ai_insights to authenticated;

-- ---------------------------------------------------------------------------
-- Owner reassignment → private Realtime broadcast to the previous owner.
--
-- postgres_changes checks RLS against the NEW row, so a rep whose prospect is
-- reassigned away never receives that UPDATE (and their Kanban would keep the
-- card). This trigger sends a broadcast (payload: only the prospect id) on the
-- private topic `user:<old owner id>`; the policy below lets each user receive
-- only their own topic. realtime.send() swallows its own errors (warning), so a
-- Realtime problem never blocks the reassignment.
-- ---------------------------------------------------------------------------
create function public.prospects_broadcast_owner_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform realtime.send(
    jsonb_build_object('prospect_id', new.id),
    'prospect_owner_changed',
    'user:' || old.owner_id::text,
    true
  );
  return null;
end;
$$;

revoke execute on function public.prospects_broadcast_owner_change() from public, anon, authenticated;

create trigger prospects_broadcast_owner_change
  after update of owner_id on public.prospects
  for each row
  when (old.owner_id is distinct from new.owner_id)
  execute function public.prospects_broadcast_owner_change();

-- Private broadcast channels: a signed-in user may join/receive only `user:<own id>`.
create policy "users receive their own broadcasts"
  on realtime.messages
  for select
  to authenticated
  using (
    realtime.messages.extension = 'broadcast'
    and (select realtime.topic()) = 'user:' || (select auth.uid())::text
  );

-- -----------------------------------------------------------------------------
-- 20261008120000_follow_ups.sql
-- -----------------------------------------------------------------------------

-- Prompt 10 (Follow-ups page): one bucketing definition for the follow-up tabs
-- and their counts, plus the latest conversation snippet per prospect.
--
-- Single source of truth: follow_up_bucket() decides the tab of a follow-up
-- relative to the org "today" (SPEC §6/§8). The follow_up_buckets view applies
-- it with now() + the org timezone, and both the tab lists and the counts RPC
-- read that view, so counts and contents can never disagree.
-- TS mirror (parity-tested): followUpViewBucket() in src/lib/time.ts.

-- ---------------------------------------------------------------------------
-- follow_up_bucket(): pure; `now` and the timezone are explicit so the org-tz
-- edge cases (11 pm New York = next day UTC, DST, Honolulu) are testable.
--   pending:   due < today → overdue · = today → today · ≤ today + 7 → upcoming · else later
--   completed: org-tz date of completed_at within the 30 org calendar days
--              ending today (≥ today − 29) → completed · else null
-- ---------------------------------------------------------------------------
create function public.follow_up_bucket(
  p_status public.follow_up_status,
  p_due_date date,
  p_completed_at timestamptz,
  p_now timestamptz,
  p_timezone text
)
returns text
language sql
immutable
set search_path = ''
as $$
  select case
    when p_status = 'pending' then
      case
        when p_due_date < t.today then 'overdue'
        when p_due_date = t.today then 'today'
        when p_due_date <= t.today + 7 then 'upcoming'
        else 'later'
      end
    when p_completed_at is not null
      and (p_completed_at at time zone p_timezone)::date >= t.today - 29 then 'completed'
    else null
  end
  from (select (p_now at time zone p_timezone)::date as today) t;
$$;

comment on function public.follow_up_bucket(public.follow_up_status, date, timestamptz, timestamptz, text) is
  'Follow-ups page tab of a follow-up relative to the org-local date of p_now: overdue/today/upcoming (≤ today+7)/later for pending, completed (last 30 org days) or null. Mirror: followUpViewBucket() in src/lib/time.ts.';

revoke execute on function public.follow_up_bucket(public.follow_up_status, date, timestamptz, timestamptz, text)
  from public, anon;
grant execute on function public.follow_up_bucket(public.follow_up_status, date, timestamptz, timestamptz, text)
  to authenticated;

-- ---------------------------------------------------------------------------
-- follow_up_buckets: follow-ups + their bucket (security_invoker → follow_ups
-- RLS: reps see their own prospects' rows, managers everything). Old completed
-- rows are filtered out before bucketing (the function makes the exact cut).
-- Selects f.*, so recreate it when follow_ups gains columns.
-- ---------------------------------------------------------------------------
create view public.follow_up_buckets
with (security_invoker = true)
as
select
  f.*,
  public.follow_up_bucket(f.status, f.due_date, f.completed_at, now(), s.timezone) as bucket
from public.follow_ups f
left join public.org_settings s on s.id
where f.status = 'pending'
   or f.completed_at >= now() - interval '32 days';

comment on view public.follow_up_buckets is
  'follow_ups + bucket (overdue/today/upcoming/later/completed, org timezone) for the Follow-ups page; same definition as follow_up_bucket_counts(). security_invoker.';

revoke all on public.follow_up_buckets from public, anon, authenticated;
grant select on public.follow_up_buckets to authenticated;

-- ---------------------------------------------------------------------------
-- follow_up_bucket_counts(): tab counts from the same view (RLS applies).
-- p_owner_id null → every follow-up the caller can see; otherwise that owner's.
-- ---------------------------------------------------------------------------
create function public.follow_up_bucket_counts(p_owner_id uuid default null)
returns table (overdue integer, today integer, upcoming integer, completed integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (count(*) filter (where b.bucket = 'overdue'))::integer,
    (count(*) filter (where b.bucket = 'today'))::integer,
    (count(*) filter (where b.bucket = 'upcoming'))::integer,
    (count(*) filter (where b.bucket = 'completed'))::integer
  from public.follow_up_buckets b
  where p_owner_id is null or b.owner_id = p_owner_id;
$$;

comment on function public.follow_up_bucket_counts(uuid) is
  'Follow-ups page tab counts (overdue/today/upcoming/completed) over follow_up_buckets; optional owner filter. Sidebar badge = overdue + today for the current user.';

revoke execute on function public.follow_up_bucket_counts(uuid) from public, anon;
grant execute on function public.follow_up_bucket_counts(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- latest_conversation_activities: newest call / conversation / note with
-- content per prospect ("last conversation" snippet). Embedded per prospect;
-- the prospect_id filter is pushed into the distinct-on → partial index lookup.
-- ---------------------------------------------------------------------------
create index activities_conversation_prospect_idx
  on public.activities (prospect_id, occurred_at desc, id desc)
  where type in ('call', 'conversation', 'note');

create view public.latest_conversation_activities
with (security_invoker = true)
as
select distinct on (a.prospect_id)
  a.prospect_id,
  a.id,
  a.type,
  a.occurred_at,
  left(a.content, 280) as snippet,
  char_length(a.content) as content_length
from public.activities a
where a.type in ('call', 'conversation', 'note')
  and a.content is not null
  and btrim(a.content) <> ''
order by a.prospect_id, a.occurred_at desc, a.id desc;

comment on view public.latest_conversation_activities is
  'Newest call/conversation/note activity with content per prospect (snippet = first 280 chars). security_invoker: RLS of activities applies.';

revoke all on public.latest_conversation_activities from public, anon, authenticated;
grant select on public.latest_conversation_activities to authenticated;

-- -----------------------------------------------------------------------------
-- 20261009120000_ai_insights.sql
-- -----------------------------------------------------------------------------

-- Prompt 11 (AI insights): rate limit on the DB clock + atomic insert of an
-- insight and its ai_insight activity.

-- ---------------------------------------------------------------------------
-- ai_insight_recent_count(): how many AI insights the caller generated in the
-- last 10 minutes (DB clock; ai_insights.created_at is not writable by users).
-- security definer so it counts the caller's own rows even when RLS would
-- hide them now (e.g. the prospect was reassigned away). It only ever reveals
-- the caller's own count. Served by ai_insights_created_by_created_at_idx.
-- Mirrors AI_RATE_LIMIT / AI_RATE_WINDOW_MINUTES in src/lib/ai/limits.ts.
-- ---------------------------------------------------------------------------
create function public.ai_insight_recent_count()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)::integer
    from public.ai_insights i
   where i.created_by = (select auth.uid())
     and i.created_at > now() - interval '10 minutes';
$$;

comment on function public.ai_insight_recent_count() is
  'AI insights generated by the caller in the last 10 minutes (rate limit, DB clock).';

revoke all on function public.ai_insight_recent_count() from public, anon;
grant execute on function public.ai_insight_recent_count() to authenticated;

-- ---------------------------------------------------------------------------
-- record_ai_insight(): stores one AI insight + its ai_insight activity in one
-- transaction (never an insight without its timeline entry). security invoker:
-- the caller's RLS + column grants apply (created_by = auth.uid() by default,
-- can_access_prospect). Re-checks the rate limit under a per-user advisory
-- lock, so parallel requests can't exceed it. The ai_insight activity does not
-- touch prospects.last_activity_at (activities_after_insert ignores it).
-- ---------------------------------------------------------------------------
create function public.record_ai_insight(
  p_prospect_id uuid,
  p_summary text,
  p_decision_maker_status public.decision_maker_status,
  p_main_objection text,
  p_recommended_next_step text,
  p_deal_health public.deal_health,
  p_model text
)
returns public.ai_insights
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_row public.ai_insights;
begin
  if v_uid is null then
    raise exception 'Not signed in' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('ai_insight:' || v_uid::text, 0));

  if public.ai_insight_recent_count() >= 10 then
    raise exception 'AI insight rate limit reached' using errcode = 'P0001';
  end if;

  insert into public.ai_insights
    (prospect_id, summary, decision_maker_status, main_objection, recommended_next_step, deal_health, model)
  values
    (p_prospect_id, p_summary, p_decision_maker_status, p_main_objection, p_recommended_next_step, p_deal_health, p_model)
  returning * into v_row;

  insert into public.activities (prospect_id, type, content, metadata)
  values (
    p_prospect_id,
    'ai_insight',
    p_summary,
    jsonb_build_object('insight_id', v_row.id, 'deal_health', v_row.deal_health)
  );

  return v_row;
end;
$$;

comment on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text) is
  'Stores an AI insight + its ai_insight activity atomically (security invoker; rate limit 10 per user per 10 minutes).';

revoke all on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text)
  from public, anon;
grant execute on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text)
  to authenticated;

-- -----------------------------------------------------------------------------
-- 20261010120000_dashboard.sql
-- -----------------------------------------------------------------------------

-- Prompt 12 (Dashboard): shared metric definitions (reused by Prompt 13
-- Reports), the latest AI next step per prospect, and the ranked
-- "deals needing attention" list. Everything is security invoker → the
-- caller's RLS applies (reps: own prospects; managers: everything).

-- ---------------------------------------------------------------------------
-- open_pipeline_value(): SPEC §12 pipeline value = sum of deal_value of open
-- (non-closed) prospects, grouped by currency (never summed across
-- currencies). Prospects without a deal value are ignored in the totals and
-- returned as ONE row with currency = null / total_value = null whose
-- prospect_count is the "N without value" count. Sum of prospect_count over
-- all rows = number of open prospects. Always "now" (no date filter).
-- Prompt 13: report_pipeline_value() wraps this function.
-- ---------------------------------------------------------------------------
create function public.open_pipeline_value(p_owner_id uuid default null)
returns table (currency text, total_value numeric, prospect_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    case when p.deal_value is null then null else p.currency::text end as currency,
    sum(p.deal_value) as total_value,
    count(*)::integer as prospect_count
  from public.prospects p
  where p.stage not in ('closed_won', 'closed_lost')
    and (p_owner_id is null or p.owner_id = p_owner_id)
  group by 1
  order by 1 nulls last;
$$;

comment on function public.open_pipeline_value(uuid) is
  'SPEC §12 pipeline value: open prospects by currency (currency null row = open prospects without a deal value; total_value null). Optional owner filter. RLS applies. Reused by report_pipeline_value().';

revoke execute on function public.open_pipeline_value(uuid) from public, anon;
grant execute on function public.open_pipeline_value(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- closed_outcome_counts(): prospects currently closed won / lost whose
-- closed_at falls on an org-tz calendar date in [p_from, p_to] (SPEC §12:
-- "win rate … for prospects closed in the selected period"). Win rate =
-- won / (won + lost), shown as "—" when both are 0. Dashboard: the 90 org days
-- ending today (p_from = today - 89). Prompt 13: report_outcomes() reuses it.
-- ---------------------------------------------------------------------------
create function public.closed_outcome_counts(p_from date, p_to date, p_owner_id uuid default null)
returns table (won integer, lost integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (count(*) filter (where p.stage = 'closed_won'))::integer as won,
    (count(*) filter (where p.stage = 'closed_lost'))::integer as lost
  from public.prospects p
  cross join (select s.timezone from public.org_settings s where s.id) tz
  where p.stage in ('closed_won', 'closed_lost')
    and p.closed_at is not null
    and (p.closed_at at time zone tz.timezone)::date between p_from and p_to
    and (p_owner_id is null or p.owner_id = p_owner_id);
$$;

comment on function public.closed_outcome_counts(date, date, uuid) is
  'Won / lost counts of prospects closed (org-tz date of closed_at) between p_from and p_to inclusive; optional owner filter. RLS applies. Win rate = won / (won + lost).';

revoke execute on function public.closed_outcome_counts(date, date, uuid) from public, anon;
grant execute on function public.closed_outcome_counts(date, date, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- latest_ai_insights: + recommended_next_step / main_objection (appended
-- columns; the Kanban embed of deal_health is unchanged).
-- ---------------------------------------------------------------------------
create or replace view public.latest_ai_insights
with (security_invoker = true)
as
select distinct on (i.prospect_id)
  i.prospect_id,
  i.id,
  i.deal_health,
  i.created_at,
  i.recommended_next_step,
  i.main_objection
from public.ai_insights i
order by i.prospect_id, i.created_at desc, i.id desc;

comment on view public.latest_ai_insights is
  'Newest AI insight per prospect (deal_health for Kanban cards; next step / main objection for the dashboard). security_invoker: RLS of ai_insights applies.';

-- ---------------------------------------------------------------------------
-- deals_needing_attention: open prospects with at least one reason, ranked
-- (SPEC §1.6). attention_rank = the highest-priority reason:
--   1 overdue follow-up > 2 stale (no human activity for stale_days)
--   > 3 latest AI deal health low > 4 no pending follow-up.
-- Order: attention_rank, follow_up_date asc nulls last (most overdue first),
-- last_activity_at asc, id. TS mirror: rankDealsNeedingAttention() in
-- src/lib/dashboard.ts (parity-checked by the integration test).
-- id = prospects.id, so latest_conversation_activities / latest_ai_insights embed.
-- ---------------------------------------------------------------------------
create view public.deals_needing_attention
with (security_invoker = true)
as
select
  f.id,
  f.name,
  f.company,
  f.stage,
  f.owner_id,
  f.follow_up_date,
  f.last_activity_at,
  f.deal_value,
  f.currency,
  f.has_overdue_follow_up,
  f.is_stale,
  coalesce(li.deal_health = 'low', false) as low_health,
  f.follow_up_date is null as no_follow_up,
  case
    when f.has_overdue_follow_up then 1
    when f.is_stale then 2
    when li.deal_health = 'low' then 3
    when f.follow_up_date is null then 4
  end as attention_rank
from public.prospects_with_flags f
left join public.latest_ai_insights li on li.prospect_id = f.id
where f.stage not in ('closed_won', 'closed_lost')
  and (
    f.has_overdue_follow_up
    or f.is_stale
    or li.deal_health = 'low'
    or f.follow_up_date is null
  );

comment on view public.deals_needing_attention is
  'Open prospects needing attention with flags + attention_rank (1 overdue follow-up, 2 stale, 3 AI health low, 4 no pending follow-up). Order by attention_rank, follow_up_date nulls last, last_activity_at, id. security_invoker.';

revoke all on public.deals_needing_attention from public, anon, authenticated;
grant select on public.deals_needing_attention to authenticated;

-- -----------------------------------------------------------------------------
-- 20261011120000_reports.sql
-- -----------------------------------------------------------------------------

-- Prompt 13 (Reports): SPEC §12 report metrics. Everything is security
-- invoker → the caller's RLS applies (reps: own prospects; managers:
-- everything). A rep passing another owner's id simply gets zeros / no rows.
--
-- Period convention: p_from … p_to are org calendar dates (inclusive) =
-- instants [p_from 00:00 org tz, (p_to + 1) 00:00 org tz). p_from > p_to →
-- error 22023. "Now" metrics (stage counts, pipeline value, overdue / due
-- today) take no dates.
--
-- Reused definitions (never re-implemented here):
--   open_pipeline_value()      (Prompt 12) → report_pipeline_value()
--   closed_outcome_counts()    (Prompt 12) → report_outcomes() won / lost
--   follow_up_bucket_counts()  (Prompt 10) → report_follow_ups() overdue / today

-- ---------------------------------------------------------------------------
-- Indexes for the period filters.
-- ---------------------------------------------------------------------------
create index prospects_created_at_idx on public.prospects (created_at);
create index prospects_closed_at_idx on public.prospects (closed_at) where closed_at is not null;
create index follow_ups_completed_at_idx on public.follow_ups (completed_at) where status = 'completed';

-- ---------------------------------------------------------------------------
-- org_period_bounds(): org calendar days [p_from, p_to] → half-open instants.
-- DST-correct (local midnight of each date in the org timezone).
-- ---------------------------------------------------------------------------
create function public.org_period_bounds(p_from date, p_to date)
returns table (start_at timestamptz, end_at timestamptz)
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  v_tz text;
begin
  if p_from is null or p_to is null then
    raise exception 'The period needs a start and an end date' using errcode = '22023';
  end if;
  if p_from > p_to then
    raise exception 'The start date must be on or before the end date' using errcode = '22023';
  end if;

  select s.timezone into v_tz from public.org_settings s where s.id;
  v_tz := coalesce(v_tz, 'America/New_York');

  start_at := p_from::timestamp at time zone v_tz;
  end_at := (p_to + 1)::timestamp at time zone v_tz;
  return next;
end;
$$;

comment on function public.org_period_bounds(date, date) is
  'Org calendar days p_from..p_to (inclusive) as half-open instants [start_at, end_at) in the org timezone. Raises 22023 when p_from > p_to.';

revoke execute on function public.org_period_bounds(date, date) from public, anon;
grant execute on function public.org_period_bounds(date, date) to authenticated;

-- ---------------------------------------------------------------------------
-- Period cohorts (RLS applies). Owner = the prospect's current owner.
-- ---------------------------------------------------------------------------
create function public.prospects_created_in_period(p_from date, p_to date, p_owner_id uuid default null)
returns setof public.prospects
language sql
stable
security invoker
set search_path = ''
as $$
  select p.*
  from public.prospects p
  cross join public.org_period_bounds(p_from, p_to) b
  where p.created_at >= b.start_at
    and p.created_at < b.end_at
    and (p_owner_id is null or p.owner_id = p_owner_id);
$$;

comment on function public.prospects_created_in_period(date, date, uuid) is
  'Prospects created in the org-tz period (funnel cohort, SPEC §12); optional current owner. RLS applies.';

revoke execute on function public.prospects_created_in_period(date, date, uuid) from public, anon;
grant execute on function public.prospects_created_in_period(date, date, uuid) to authenticated;

create function public.prospects_closed_in_period(p_from date, p_to date, p_owner_id uuid default null)
returns setof public.prospects
language sql
stable
security invoker
set search_path = ''
as $$
  select p.*
  from public.prospects p
  cross join public.org_period_bounds(p_from, p_to) b
  where p.stage in ('closed_won', 'closed_lost')
    and p.closed_at >= b.start_at
    and p.closed_at < b.end_at
    and (p_owner_id is null or p.owner_id = p_owner_id);
$$;

comment on function public.prospects_closed_in_period(date, date, uuid) is
  'Prospects currently closed won/lost whose closed_at falls in the org-tz period (win rate / won value basis, SPEC §12); optional owner. RLS applies.';

revoke execute on function public.prospects_closed_in_period(date, date, uuid) from public, anon;
grant execute on function public.prospects_closed_in_period(date, date, uuid) to authenticated;

-- Prompt 12's closed_outcome_counts(), now on top of the shared period helper
-- (same signature and results: org-tz date of closed_at in [p_from, p_to]).
create or replace function public.closed_outcome_counts(p_from date, p_to date, p_owner_id uuid default null)
returns table (won integer, lost integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    (count(*) filter (where c.stage = 'closed_won'))::integer as won,
    (count(*) filter (where c.stage = 'closed_lost'))::integer as lost
  from public.prospects_closed_in_period(p_from, p_to, p_owner_id) c;
$$;

-- ---------------------------------------------------------------------------
-- stage_funnel_rank(): SPEC §2 order for the funnel; closed_lost unranked.
-- prospect 1 · contacted 2 · conversation 3 · qualified 4 · demo_booked 5 ·
-- demo_attended 6 · follow_up 7 · closed_won 8 · closed_lost null
-- ---------------------------------------------------------------------------
create function public.stage_funnel_rank(p_stage public.pipeline_stage)
returns integer
language sql
immutable
set search_path = ''
as $$
  select array_position(
    array['prospect', 'contacted', 'conversation', 'qualified', 'demo_booked',
          'demo_attended', 'follow_up', 'closed_won']::public.pipeline_stage[],
    p_stage
  );
$$;

comment on function public.stage_funnel_rank(public.pipeline_stage) is
  'Funnel rank of a stage (SPEC §2 order, 1..8); closed_lost is unranked (null).';

revoke execute on function public.stage_funnel_rank(public.pipeline_stage) from public, anon;
grant execute on function public.stage_funnel_rank(public.pipeline_stage) to authenticated;

-- ---------------------------------------------------------------------------
-- report_stage_counts(): prospects by CURRENT stage ("now", not period
-- filtered), all 9 stages in SPEC order, zero-filled. Total = sum.
-- ---------------------------------------------------------------------------
create function public.report_stage_counts(p_owner_id uuid default null)
returns table (stage public.pipeline_stage, prospect_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select s.stage, count(p.id)::integer as prospect_count
  from unnest(enum_range(null::public.pipeline_stage)) with ordinality as s(stage, ord)
  left join public.prospects p
    on p.stage = s.stage
   and (p_owner_id is null or p.owner_id = p_owner_id)
  group by s.stage, s.ord
  order by s.ord;
$$;

comment on function public.report_stage_counts(uuid) is
  'Prospects by current stage (now), 9 rows in SPEC order, zero-filled; optional owner. RLS applies.';

revoke execute on function public.report_stage_counts(uuid) from public, anon;
grant execute on function public.report_stage_counts(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- report_stage_reached(): for prospects CREATED in the period, how many
-- reached at least each ranked stage. Highest stage ever reached = max
-- stage_funnel_rank over every stage_history row (from + to) and the current
-- stage; a prospect with no ranked stage at all (e.g. created as closed_lost)
-- counts as "prospect". Skips count the skipped stages, backward moves never
-- lower the reach, a reopened deal that ends won reaches closed_won.
-- One definition for the funnel AND the SPEC §12 stage counts.
-- ---------------------------------------------------------------------------
create function public.report_stage_reached(p_from date, p_to date, p_owner_id uuid default null)
returns table (stage public.pipeline_stage, stage_rank integer, prospect_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  with reached as (
    select coalesce(
      greatest(
        public.stage_funnel_rank(c.stage),
        (
          select max(greatest(public.stage_funnel_rank(h.from_stage), public.stage_funnel_rank(h.to_stage)))
          from public.stage_history h
          where h.prospect_id = c.id
        )
      ),
      1
    ) as max_rank
    from public.prospects_created_in_period(p_from, p_to, p_owner_id) c
  ),
  ranked as (
    select s.stage, public.stage_funnel_rank(s.stage) as stage_rank
    from unnest(enum_range(null::public.pipeline_stage)) as s(stage)
    where public.stage_funnel_rank(s.stage) is not null
  )
  select
    r.stage,
    r.stage_rank,
    (select count(*) from reached x where x.max_rank >= r.stage_rank)::integer as prospect_count
  from ranked r
  order by r.stage_rank;
$$;

comment on function public.report_stage_reached(date, date, uuid) is
  'Prospects created in the period whose highest stage ever reached (stage_history + current, SPEC §2 order, closed_lost unranked) is >= each ranked stage. 8 rows. RLS applies.';

revoke execute on function public.report_stage_reached(date, date, uuid) from public, anon;
grant execute on function public.report_stage_reached(date, date, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- report_funnel(): SPEC §12 funnel Prospects → Contacted → Conversation →
-- Qualified → Demo Booked → Demo Attended → Closed Won (follow_up is not a
-- step, but reaching it implies ≥ Demo Attended). Percentages rounded to 1
-- decimal: step = 100 × count ÷ previous step (null for step 1 / previous 0),
-- overall = 100 × count ÷ Prospects (null when 0; Closed Won row = SPEC
-- "overall conversion").
-- ---------------------------------------------------------------------------
create function public.report_funnel(p_from date, p_to date, p_owner_id uuid default null)
returns table (
  step integer,
  stage public.pipeline_stage,
  prospect_count integer,
  step_conversion_pct numeric,
  overall_conversion_pct numeric
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    f.step,
    f.stage,
    f.prospect_count,
    case when f.previous_count is null or f.previous_count = 0 then null
         else round(100.0 * f.prospect_count / f.previous_count, 1) end,
    case when f.first_count = 0 then null
         else round(100.0 * f.prospect_count / f.first_count, 1) end
  from (
    select
      (row_number() over w)::integer as step,
      r.stage,
      r.prospect_count,
      lag(r.prospect_count) over w as previous_count,
      first_value(r.prospect_count) over w as first_count
    from public.report_stage_reached(p_from, p_to, p_owner_id) r
    where r.stage <> 'follow_up'
    window w as (order by r.stage_rank)
  ) f
  order by f.step;
$$;

comment on function public.report_funnel(date, date, uuid) is
  'SPEC §12 funnel for prospects created in the period: 7 steps with counts, step conversion % (vs previous step) and overall % (vs Prospects). RLS applies.';

revoke execute on function public.report_funnel(date, date, uuid) from public, anon;
grant execute on function public.report_funnel(date, date, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- report_outcomes(): prospects closed in the period (current state). won /
-- lost via closed_outcome_counts(); win rate % (1 decimal, null when none
-- closed); won value per currency (nulls ignored, never summed across
-- currencies) + won deals without a value; lost-reason breakdown.
-- ---------------------------------------------------------------------------
create function public.report_outcomes(p_from date, p_to date, p_owner_id uuid default null)
returns table (
  won integer,
  lost integer,
  win_rate_pct numeric,
  won_value jsonb,
  won_without_value integer,
  lost_reasons jsonb
)
language sql
stable
security invoker
set search_path = ''
as $$
  with closed as (
    select c.stage, c.deal_value, c.currency, c.close_reason
    from public.prospects_closed_in_period(p_from, p_to, p_owner_id) c
  )
  select
    o.won,
    o.lost,
    case when o.won + o.lost = 0 then null
         else round(100.0 * o.won / (o.won + o.lost), 1) end as win_rate_pct,
    coalesce((
      select jsonb_agg(jsonb_build_object('currency', v.currency, 'total', v.total, 'count', v.n) order by v.currency)
      from (
        select x.currency::text as currency, sum(x.deal_value) as total, count(*)::integer as n
        from closed x
        where x.stage = 'closed_won' and x.deal_value is not null
        group by 1
      ) v
    ), '[]'::jsonb) as won_value,
    (select count(*) from closed x where x.stage = 'closed_won' and x.deal_value is null)::integer as won_without_value,
    coalesce((
      select jsonb_agg(jsonb_build_object('reason', l.reason, 'count', l.n) order by l.n desc, l.reason)
      from (
        select x.close_reason as reason, count(*)::integer as n
        from closed x
        where x.stage = 'closed_lost'
        group by 1
      ) l
    ), '[]'::jsonb) as lost_reasons
  from public.closed_outcome_counts(p_from, p_to, p_owner_id) o;
$$;

comment on function public.report_outcomes(date, date, uuid) is
  'Prospects closed in the period: won, lost, win rate % (null when none), won value per currency [{currency,total,count}], won deals without value, lost reasons [{reason,count}]. RLS applies.';

revoke execute on function public.report_outcomes(date, date, uuid) from public, anon;
grant execute on function public.report_outcomes(date, date, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- report_pipeline_value(): always "now" — exactly open_pipeline_value().
-- ---------------------------------------------------------------------------
create function public.report_pipeline_value(p_owner_id uuid default null)
returns table (currency text, total_value numeric, prospect_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select v.currency, v.total_value, v.prospect_count
  from public.open_pipeline_value(p_owner_id) v;
$$;

comment on function public.report_pipeline_value(uuid) is
  'SPEC §12 pipeline value (now) = open_pipeline_value(): per currency + a currency-null row counting open prospects without a value. RLS applies.';

revoke execute on function public.report_pipeline_value(uuid) from public, anon;
grant execute on function public.report_pipeline_value(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- report_follow_ups(): overdue + due today NOW (follow_up_bucket_counts, the
-- Follow-ups page definition) and follow-ups completed in the period.
-- Owner = follow_ups.owner_id (as on the Follow-ups page).
-- ---------------------------------------------------------------------------
create function public.report_follow_ups(p_from date, p_to date, p_owner_id uuid default null)
returns table (overdue integer, due_today integer, completed integer)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    c.overdue,
    c.today as due_today,
    (
      select count(*)
      from public.follow_ups f
      cross join public.org_period_bounds(p_from, p_to) b
      where f.status = 'completed'
        and f.completed_at >= b.start_at
        and f.completed_at < b.end_at
        and (p_owner_id is null or f.owner_id = p_owner_id)
    )::integer as completed
  from public.follow_up_bucket_counts(p_owner_id) c;
$$;

comment on function public.report_follow_ups(date, date, uuid) is
  'Follow-up counts: overdue and due today now (follow_up_bucket_counts) + completed in the org-tz period; optional owner. RLS applies.';

revoke execute on function public.report_follow_ups(date, date, uuid) from public, anon;
grant execute on function public.report_follow_ups(date, date, uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- 20261012120000_service_role_grants.sql
-- -----------------------------------------------------------------------------

-- Explicit privileges for service_role (server-only key: admin scripts such as
-- create-manager / demo-data and manager-verified invites).
--
-- Locally and on most projects service_role already has these through
-- Supabase's default privileges; newer projects may not grant them to new
-- tables automatically, so they are stated explicitly here. service_role
-- bypasses RLS; it is never used in user-facing code paths (see CLAUDE.md).

grant usage on schema public to service_role;
grant all on all tables in schema public to service_role;
grant all on all sequences in schema public to service_role;
grant execute on all functions in schema public to service_role;

alter default privileges for role postgres in schema public grant all on tables to service_role;
alter default privileges for role postgres in schema public grant all on sequences to service_role;
alter default privileges for role postgres in schema public grant execute on functions to service_role;

-- -----------------------------------------------------------------------------
-- 20261013120000_backfill_users.sql
-- -----------------------------------------------------------------------------

-- Backfill public.users for auth users created before the CRM schema existed
-- (e.g. accounts added in the Supabase dashboard before the first migration
-- ran, so the on_auth_user_created trigger wasn't there yet). Same values as
-- public.handle_new_user(); idempotent; a no-op when every auth user already
-- has a profile (always the case on a fresh local reset: the seed runs later).

insert into public.users (id, email, full_name, role)
select
  a.id,
  coalesce(a.email, ''),
  coalesce(
    nullif(btrim(a.raw_user_meta_data ->> 'full_name'), ''),
    split_part(coalesce(a.email, ''), '@', 1)
  ),
  case
    when a.raw_app_meta_data ->> 'role' in ('manager', 'sales_rep')
      then (a.raw_app_meta_data ->> 'role')::public.user_role
    else 'sales_rep'::public.user_role
  end
from auth.users a
where not exists (select 1 from public.users u where u.id = a.id);

-- -----------------------------------------------------------------------------
-- 20261014120000_dashboard_charts.sql
-- -----------------------------------------------------------------------------

-- Dashboard charts: daily activity, weekly new-vs-won flow, team summary.
-- All security invoker (RLS applies: reps only ever count their own rows) and
-- bucketed by org-timezone calendar days ending org_today().

-- ---------------------------------------------------------------------------
-- Human sales activity per org day (SPEC §7 types that move last_activity_at),
-- zero-filled, oldest first. Owner = the prospect's current owner.
-- ---------------------------------------------------------------------------
create function public.dashboard_daily_activity(p_days integer default 14, p_owner_id uuid default null)
returns table (day date, activity_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  with bounds as (
    select
      public.org_today() as today,
      greatest(least(coalesce(p_days, 14), 90), 1) as n,
      coalesce((select s.timezone from public.org_settings s where s.id), 'America/New_York') as tz
  ),
  days as (
    select (b.today - g)::date as day
    from bounds b, generate_series(0, b.n - 1) as g
  ),
  acts as (
    select (a.occurred_at at time zone b.tz)::date as day
    from public.activities a
    join public.prospects p on p.id = a.prospect_id
    cross join bounds b
    where a.type in ('call', 'conversation', 'note', 'demo', 'follow_up', 'stage_change')
      and a.occurred_at >= ((b.today - (b.n - 1))::timestamp at time zone b.tz)
      and a.occurred_at < ((b.today + 1)::timestamp at time zone b.tz)
      and (p_owner_id is null or p.owner_id = p_owner_id)
  )
  select d.day, count(a.day)::integer as activity_count
  from days d
  left join acts a on a.day = d.day
  group by d.day
  order by d.day;
$$;

comment on function public.dashboard_daily_activity(integer, uuid) is
  'Human activities (call, conversation, note, demo, follow_up, stage_change) per org day for the last p_days days ending org_today(), zero-filled. RLS applies.';

revoke execute on function public.dashboard_daily_activity(integer, uuid) from public, anon;
grant execute on function public.dashboard_daily_activity(integer, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Rolling 7-day windows ending org_today(): prospects created vs deals won
-- (currently closed_won, closed_at in the window). Oldest window first.
-- ---------------------------------------------------------------------------
create function public.dashboard_weekly_flow(p_weeks integer default 8, p_owner_id uuid default null)
returns table (week_start date, week_end date, created_count integer, won_count integer)
language sql
stable
security invoker
set search_path = ''
as $$
  with bounds as (
    select
      public.org_today() as today,
      greatest(least(coalesce(p_weeks, 8), 26), 1) as n,
      coalesce((select s.timezone from public.org_settings s where s.id), 'America/New_York') as tz
  ),
  weeks as (
    select (b.today - 7 * g - 6)::date as week_start, (b.today - 7 * g)::date as week_end
    from bounds b, generate_series(0, b.n - 1) as g
  ),
  scoped as (
    select p.created_at, p.closed_at, p.stage
    from public.prospects p
    where p_owner_id is null or p.owner_id = p_owner_id
  )
  select
    w.week_start,
    w.week_end,
    (select count(*) from scoped s, bounds b
      where (s.created_at at time zone b.tz)::date between w.week_start and w.week_end)::integer as created_count,
    (select count(*) from scoped s, bounds b
      where s.stage = 'closed_won'
        and (s.closed_at at time zone b.tz)::date between w.week_start and w.week_end)::integer as won_count
  from weeks w
  order by w.week_start;
$$;

comment on function public.dashboard_weekly_flow(integer, uuid) is
  'Rolling 7-day windows ending org_today(): prospects created and deals won per window, oldest first. RLS applies.';

revoke execute on function public.dashboard_weekly_flow(integer, uuid) from public, anon;
grant execute on function public.dashboard_weekly_flow(integer, uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- One row per sales rep: open deals, stale deals, overdue follow-ups and
-- won / lost in the last 90 org days. RLS applies (a rep sees only their own
-- numbers; the other reps' rows come back as zeros).
-- ---------------------------------------------------------------------------
create function public.dashboard_team_summary()
returns table (
  user_id uuid,
  open_count integer,
  stale_count integer,
  overdue_count integer,
  won_count integer,
  lost_count integer
)
language sql
stable
security invoker
set search_path = ''
as $$
  select
    u.id as user_id,
    (select count(*) from public.prospects_with_flags p
      where p.owner_id = u.id and p.stage not in ('closed_won', 'closed_lost'))::integer as open_count,
    (select count(*) from public.prospects_with_flags p
      where p.owner_id = u.id and p.is_stale)::integer as stale_count,
    (select count(*) from public.follow_ups f
      where f.owner_id = u.id and f.status = 'pending' and f.due_date < public.org_today())::integer as overdue_count,
    o.won as won_count,
    o.lost as lost_count
  from public.users u
  cross join lateral public.closed_outcome_counts(public.org_today() - 89, public.org_today(), u.id) o
  where u.role = 'sales_rep'
  order by u.full_name, u.id;
$$;

comment on function public.dashboard_team_summary() is
  'Per sales rep: open, stale, overdue follow-ups, won/lost in the last 90 org days. RLS applies.';

revoke execute on function public.dashboard_team_summary() from public, anon;
grant execute on function public.dashboard_team_summary() to authenticated;

-- -----------------------------------------------------------------------------
-- Migration history (same table the Supabase CLI uses)
-- -----------------------------------------------------------------------------

create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text not null primary key,
  statements text[],
  name text
);
insert into supabase_migrations.schema_migrations (version, name)
values
  ('20261005120000', 'schema'),
  ('20261005120100', 'functions_triggers'),
  ('20261006120000', 'rls'),
  ('20261007120000', 'pipeline'),
  ('20261008120000', 'follow_ups'),
  ('20261009120000', 'ai_insights'),
  ('20261010120000', 'dashboard'),
  ('20261011120000', 'reports'),
  ('20261012120000', 'service_role_grants'),
  ('20261013120000', 'backfill_users'),
  ('20261014120000', 'dashboard_charts')
on conflict (version) do nothing;

commit;
