/**
 * Bundles supabase/migrations/*.sql into ONE script for a brand-new Supabase
 * project, to paste into the dashboard's SQL Editor (no CLI login or database
 * password needed):
 *
 *   npm run db:setup-sql   →  supabase/setup/production-setup.sql
 *
 * The script runs in a single transaction (all or nothing), refuses to run on
 * a project that is already set up, and records every migration in
 * supabase_migrations.schema_migrations exactly like `supabase db push`, so
 * later migrations can be applied with the CLI as usual.
 *
 * First-time setup only. Regenerate after adding migrations (CI-free check:
 * `git diff` should show the change). Never includes supabase/seed.sql.
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const MIGRATIONS_DIR = "supabase/migrations";
const OUT_DIR = "supabase/setup";
const OUT_FILE = join(OUT_DIR, "production-setup.sql");

const files = readdirSync(MIGRATIONS_DIR)
  .filter((f) => /^\d{14}_[a-z0-9_]+\.sql$/.test(f))
  .sort();
if (files.length === 0) throw new Error(`No migrations found in ${MIGRATIONS_DIR}`);

const migrations = files.map((file) => {
  const [, version, name] = /^(\d{14})_(.+)\.sql$/.exec(file)!;
  const sql = readFileSync(join(MIGRATIONS_DIR, file), "utf8").trimEnd();
  if (/^\s*(begin|commit|rollback)\s*;/im.test(sql)) {
    throw new Error(`${file} contains its own transaction control; it can't be bundled.`);
  }
  return { file, version, name, sql };
});

const quote = (s: string) => `'${s.replaceAll("'", "''")}'`;

const out = `-- =============================================================================
-- AI Sales CRM: first-time database setup for a NEW Supabase project.
--
-- GENERATED by \`npm run db:setup-sql\` from supabase/migrations. Do not edit.
-- Migrations: ${migrations.map((m) => m.version).join(", ")}
--
-- How to use: Supabase dashboard → SQL Editor → New query → paste this whole
-- file → Run. It runs in one transaction (all or nothing), refuses to run if
-- the CRM tables already exist, and records the migrations in
-- supabase_migrations.schema_migrations so \`supabase db push\` keeps working
-- for future migrations. No demo/seed data and no users are created.
-- =============================================================================

begin;

do $setup$
begin
  if to_regclass('public.prospects') is not null then
    raise exception 'The CRM tables already exist in this project. This script is for a new project only; apply new migrations with "npx supabase db push".';
  end if;
end
$setup$;

${migrations
  .map(
    (m) => `-- -----------------------------------------------------------------------------
-- ${m.file}
-- -----------------------------------------------------------------------------

${m.sql}
`,
  )
  .join("\n")}
-- -----------------------------------------------------------------------------
-- Migration history (same table the Supabase CLI uses)
-- -----------------------------------------------------------------------------

create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version text not null primary key,
  statements text[],
  name text
);
insert into supabase_migrations.schema_migrations (version, name)
values
${migrations.map((m) => `  (${quote(m.version)}, ${quote(m.name)})`).join(",\n")}
on conflict (version) do nothing;

commit;
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT_FILE, out);
console.log(`Wrote ${OUT_FILE} (${migrations.length} migrations, ${(out.length / 1024).toFixed(1)} KB).`);
