-- Prompt 11 (AI insights): rate limit on the DB clock + atomic insert of an
-- insight and its ai_insight activity.

-- ---------------------------------------------------------------------------
-- ai_insight_recent_count(): how many AI insights the caller generated in the
-- last 10 minutes (DB clock; ai_insights.created_at is not writable by users).
-- security definer so it counts the caller's own rows even when RLS would
-- hide them now (e.g. the prospect was reassigned away). It only ever reveals
-- the caller's own count. Served by ai_insights_created_by_created_at_idx.
-- Mirrors AI_RATE_LIMIT / AI_RATE_WINDOW_MINUTES in src/lib/ai/limits.ts.
-- ---------------------------------------------------------------------------
create function public.ai_insight_recent_count()
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select count(*)::integer
    from public.ai_insights i
   where i.created_by = (select auth.uid())
     and i.created_at > now() - interval '10 minutes';
$$;

comment on function public.ai_insight_recent_count() is
  'AI insights generated by the caller in the last 10 minutes (rate limit, DB clock).';

revoke all on function public.ai_insight_recent_count() from public, anon;
grant execute on function public.ai_insight_recent_count() to authenticated;

-- ---------------------------------------------------------------------------
-- record_ai_insight(): stores one AI insight + its ai_insight activity in one
-- transaction (never an insight without its timeline entry). security invoker:
-- the caller's RLS + column grants apply (created_by = auth.uid() by default,
-- can_access_prospect). Re-checks the rate limit under a per-user advisory
-- lock, so parallel requests can't exceed it. The ai_insight activity does not
-- touch prospects.last_activity_at (activities_after_insert ignores it).
-- ---------------------------------------------------------------------------
create function public.record_ai_insight(
  p_prospect_id uuid,
  p_summary text,
  p_decision_maker_status public.decision_maker_status,
  p_main_objection text,
  p_recommended_next_step text,
  p_deal_health public.deal_health,
  p_model text
)
returns public.ai_insights
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_row public.ai_insights;
begin
  if v_uid is null then
    raise exception 'Not signed in' using errcode = '42501';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('ai_insight:' || v_uid::text, 0));

  if public.ai_insight_recent_count() >= 10 then
    raise exception 'AI insight rate limit reached' using errcode = 'P0001';
  end if;

  insert into public.ai_insights
    (prospect_id, summary, decision_maker_status, main_objection, recommended_next_step, deal_health, model)
  values
    (p_prospect_id, p_summary, p_decision_maker_status, p_main_objection, p_recommended_next_step, p_deal_health, p_model)
  returning * into v_row;

  insert into public.activities (prospect_id, type, content, metadata)
  values (
    p_prospect_id,
    'ai_insight',
    p_summary,
    jsonb_build_object('insight_id', v_row.id, 'deal_health', v_row.deal_health)
  );

  return v_row;
end;
$$;

comment on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text) is
  'Stores an AI insight + its ai_insight activity atomically (security invoker; rate limit 10 per user per 10 minutes).';

revoke all on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text)
  from public, anon;
grant execute on function public.record_ai_insight(uuid, text, public.decision_maker_status, text, text, public.deal_health, text)
  to authenticated;
